### ISSUE TITLE
saes训练出错

### ISSUE THREAD

**Issue by yanlin1995** [xiaochus/TrafficFlowPrediction#11]
Traceback (most recent call last):
  File "E:/AI/PythonCode/TrafficFlowPrediction-master/train.py", line 108, in <module>
    main(sys.argv)
  File "E:/AI/PythonCode/TrafficFlowPrediction-master/train.py", line 104, in main
    train_seas(m, X_train, y_train, args.model, config)
  File "E:/AI/PythonCode/TrafficFlowPrediction-master/train.py", line 59, in train_seas
    hidden_layer_model = Model(input=p.input,output=p.get_layer('hidden').output)
  File "E:\AI\pythonIDE\lib\site-packages\tensorflow\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "E:\AI\pythonIDE\lib\site-packages\tensorflow\python\keras\engine\training.py", line 262, in __init__
    'name', 'autocast'})
  File "E:\AI\pythonIDE\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 778, in validate_kwargs
    raise TypeError(error_message, kwarg)
TypeError: ('Keyword argument not understood:', 'input')

Process finished with exit code 1

**Comment by Fran0727** [comment]
same issue, did you know how to fix it?
